# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Abrir.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(532, 364)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../../../Downloads/2x/baseline_folder_open_black_18dp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 531, 31))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 30, 531, 241))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.verticalLayoutWidget_2)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 527, 237))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.tblAudios = QtWidgets.QTableView(self.scrollAreaWidgetContents)
        self.tblAudios.setGeometry(QtCore.QRect(-5, 1, 531, 241))
        self.tblAudios.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.tblAudios.setEditTriggers(QtWidgets.QAbstractItemView.SelectedClicked)
        self.tblAudios.setDragDropOverwriteMode(False)
        self.tblAudios.setAlternatingRowColors(True)
        self.tblAudios.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tblAudios.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tblAudios.setShowGrid(True)
        self.tblAudios.setSortingEnabled(True)
        self.tblAudios.setObjectName("tblAudios")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(390, 270, 141, 41))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btnAbrir = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.btnAbrir.setObjectName("btnAbrir")
        self.verticalLayout_3.addWidget(self.btnAbrir)
        self.gridLayoutWidget_13 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_13.setGeometry(QtCore.QRect(0, 270, 41, 41))
        self.gridLayoutWidget_13.setObjectName("gridLayoutWidget_13")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.gridLayoutWidget_13)
        self.gridLayout_13.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.btnReproducir = QtWidgets.QToolButton(self.gridLayoutWidget_13)
        self.btnReproducir.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnReproducir.sizePolicy().hasHeightForWidth())
        self.btnReproducir.setSizePolicy(sizePolicy)
        self.btnReproducir.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.btnReproducir.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../../../../../../Downloads/2x/baseline_play_circle_filled_black_18dp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnReproducir.setIcon(icon1)
        self.btnReproducir.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.btnReproducir.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.btnReproducir.setObjectName("btnReproducir")
        self.gridLayout_13.addWidget(self.btnReproducir, 0, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.gridLayoutWidget_14 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_14.setGeometry(QtCore.QRect(40, 270, 41, 41))
        self.gridLayoutWidget_14.setObjectName("gridLayoutWidget_14")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.gridLayoutWidget_14)
        self.gridLayout_14.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.btnPausar = QtWidgets.QToolButton(self.gridLayoutWidget_14)
        self.btnPausar.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnPausar.sizePolicy().hasHeightForWidth())
        self.btnPausar.setSizePolicy(sizePolicy)
        self.btnPausar.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.btnPausar.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../../../../../../Downloads/2x/baseline_pause_circle_filled_black_18dp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPausar.setIcon(icon2)
        self.btnPausar.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.btnPausar.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.btnPausar.setObjectName("btnPausar")
        self.gridLayout_14.addWidget(self.btnPausar, 0, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.gridLayoutWidget_15 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_15.setGeometry(QtCore.QRect(80, 270, 41, 41))
        self.gridLayoutWidget_15.setObjectName("gridLayoutWidget_15")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.gridLayoutWidget_15)
        self.gridLayout_15.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.btnRepetirRep = QtWidgets.QToolButton(self.gridLayoutWidget_15)
        self.btnRepetirRep.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnRepetirRep.sizePolicy().hasHeightForWidth())
        self.btnRepetirRep.setSizePolicy(sizePolicy)
        self.btnRepetirRep.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.btnRepetirRep.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../../../../../../../Downloads/2x/baseline_first_page_black_18dp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnRepetirRep.setIcon(icon3)
        self.btnRepetirRep.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.btnRepetirRep.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.btnRepetirRep.setObjectName("btnRepetirRep")
        self.gridLayout_15.addWidget(self.btnRepetirRep, 0, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 532, 21))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionGrabar_Audio = QtWidgets.QAction(MainWindow)
        self.actionGrabar_Audio.setObjectName("actionGrabar_Audio")
        self.actionAbrir_Audio = QtWidgets.QAction(MainWindow)
        self.actionAbrir_Audio.setEnabled(False)
        self.actionAbrir_Audio.setObjectName("actionAbrir_Audio")
        self.actionAbrir_Analisis = QtWidgets.QAction(MainWindow)
        self.actionAbrir_Analisis.setEnabled(False)
        self.actionAbrir_Analisis.setObjectName("actionAbrir_Analisis")
        self.menuMenu.addAction(self.actionGrabar_Audio)
        self.menuMenu.addSeparator()
        self.menuMenu.addAction(self.actionAbrir_Audio)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Abrir Audio"))
        self.label.setText(_translate("MainWindow", "Seleccione una grabación"))
        self.btnAbrir.setText(_translate("MainWindow", "Abrir"))
        self.btnReproducir.setToolTip(_translate("MainWindow", "Iniciar Reproducción"))
        self.btnReproducir.setShortcut(_translate("MainWindow", "G"))
        self.btnPausar.setToolTip(_translate("MainWindow", "Pausar Reproducción"))
        self.btnPausar.setShortcut(_translate("MainWindow", "G"))
        self.btnRepetirRep.setToolTip(_translate("MainWindow", "Reiniciar Reproducción"))
        self.btnRepetirRep.setShortcut(_translate("MainWindow", "G"))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))
        self.actionGrabar_Audio.setText(_translate("MainWindow", "Grabar Audio"))
        self.actionAbrir_Audio.setText(_translate("MainWindow", "Abrir Audio"))
        self.actionAbrir_Analisis.setText(_translate("MainWindow", "Abrir Analisis"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
