# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Analisis.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(573, 364)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../../../Downloads/2x/baseline_graphic_eq_black_18dp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 251, 31))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblOrig = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lblOrig.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lblOrig.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lblOrig.setObjectName("lblOrig")
        self.verticalLayout.addWidget(self.lblOrig)
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(270, 0, 31, 131))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.line = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 0, 0, 1, 1)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 40, 251, 51))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.orgBarOrig = QtWidgets.QProgressBar(self.verticalLayoutWidget_2)
        self.orgBarOrig.setProperty("value", 24)
        self.orgBarOrig.setTextVisible(False)
        self.orgBarOrig.setTextDirection(QtWidgets.QProgressBar.BottomToTop)
        self.orgBarOrig.setObjectName("orgBarOrig")
        self.verticalLayout_2.addWidget(self.orgBarOrig)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(310, 40, 251, 51))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.orgBarMel = QtWidgets.QProgressBar(self.verticalLayoutWidget_3)
        self.orgBarMel.setProperty("value", 24)
        self.orgBarMel.setTextVisible(False)
        self.orgBarMel.setTextDirection(QtWidgets.QProgressBar.BottomToTop)
        self.orgBarMel.setObjectName("orgBarMel")
        self.verticalLayout_3.addWidget(self.orgBarMel)
        self.gridLayoutWidget_15 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_15.setGeometry(QtCore.QRect(150, 90, 41, 41))
        self.gridLayoutWidget_15.setObjectName("gridLayoutWidget_15")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.gridLayoutWidget_15)
        self.gridLayout_15.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.btnRepetirOrig = QtWidgets.QToolButton(self.gridLayoutWidget_15)
        self.btnRepetirOrig.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnRepetirOrig.sizePolicy().hasHeightForWidth())
        self.btnRepetirOrig.setSizePolicy(sizePolicy)
        self.btnRepetirOrig.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.btnRepetirOrig.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../../../../../../Downloads/2x/baseline_first_page_black_18dp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnRepetirOrig.setIcon(icon1)
        self.btnRepetirOrig.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.btnRepetirOrig.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.btnRepetirOrig.setObjectName("btnRepetirOrig")
        self.gridLayout_15.addWidget(self.btnRepetirOrig, 0, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.gridLayoutWidget_14 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_14.setGeometry(QtCore.QRect(110, 90, 41, 41))
        self.gridLayoutWidget_14.setObjectName("gridLayoutWidget_14")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.gridLayoutWidget_14)
        self.gridLayout_14.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.btnPausarOrig = QtWidgets.QToolButton(self.gridLayoutWidget_14)
        self.btnPausarOrig.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnPausarOrig.sizePolicy().hasHeightForWidth())
        self.btnPausarOrig.setSizePolicy(sizePolicy)
        self.btnPausarOrig.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.btnPausarOrig.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../../../../../../Downloads/2x/baseline_pause_circle_filled_black_18dp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPausarOrig.setIcon(icon2)
        self.btnPausarOrig.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.btnPausarOrig.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.btnPausarOrig.setObjectName("btnPausarOrig")
        self.gridLayout_14.addWidget(self.btnPausarOrig, 0, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.gridLayoutWidget_13 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_13.setGeometry(QtCore.QRect(70, 90, 41, 41))
        self.gridLayoutWidget_13.setObjectName("gridLayoutWidget_13")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.gridLayoutWidget_13)
        self.gridLayout_13.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.btnReproducirOrig = QtWidgets.QToolButton(self.gridLayoutWidget_13)
        self.btnReproducirOrig.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnReproducirOrig.sizePolicy().hasHeightForWidth())
        self.btnReproducirOrig.setSizePolicy(sizePolicy)
        self.btnReproducirOrig.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.btnReproducirOrig.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../../../../../../../Downloads/2x/baseline_play_circle_filled_black_18dp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnReproducirOrig.setIcon(icon3)
        self.btnReproducirOrig.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.btnReproducirOrig.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.btnReproducirOrig.setObjectName("btnReproducirOrig")
        self.gridLayout_13.addWidget(self.btnReproducirOrig, 0, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.gridLayoutWidget_16 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_16.setGeometry(QtCore.QRect(460, 90, 41, 41))
        self.gridLayoutWidget_16.setObjectName("gridLayoutWidget_16")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.gridLayoutWidget_16)
        self.gridLayout_16.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.btnRepetirMel = QtWidgets.QToolButton(self.gridLayoutWidget_16)
        self.btnRepetirMel.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnRepetirMel.sizePolicy().hasHeightForWidth())
        self.btnRepetirMel.setSizePolicy(sizePolicy)
        self.btnRepetirMel.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.btnRepetirMel.setText("")
        self.btnRepetirMel.setIcon(icon1)
        self.btnRepetirMel.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.btnRepetirMel.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.btnRepetirMel.setObjectName("btnRepetirMel")
        self.gridLayout_16.addWidget(self.btnRepetirMel, 0, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.gridLayoutWidget_17 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_17.setGeometry(QtCore.QRect(420, 90, 41, 41))
        self.gridLayoutWidget_17.setObjectName("gridLayoutWidget_17")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.gridLayoutWidget_17)
        self.gridLayout_17.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.btnPausarMel = QtWidgets.QToolButton(self.gridLayoutWidget_17)
        self.btnPausarMel.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnPausarMel.sizePolicy().hasHeightForWidth())
        self.btnPausarMel.setSizePolicy(sizePolicy)
        self.btnPausarMel.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.btnPausarMel.setText("")
        self.btnPausarMel.setIcon(icon2)
        self.btnPausarMel.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.btnPausarMel.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.btnPausarMel.setObjectName("btnPausarMel")
        self.gridLayout_17.addWidget(self.btnPausarMel, 0, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.gridLayoutWidget_18 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_18.setGeometry(QtCore.QRect(380, 90, 41, 41))
        self.gridLayoutWidget_18.setObjectName("gridLayoutWidget_18")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.gridLayoutWidget_18)
        self.gridLayout_18.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.btnReproducirMel = QtWidgets.QToolButton(self.gridLayoutWidget_18)
        self.btnReproducirMel.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnReproducirMel.sizePolicy().hasHeightForWidth())
        self.btnReproducirMel.setSizePolicy(sizePolicy)
        self.btnReproducirMel.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.btnReproducirMel.setText("")
        self.btnReproducirMel.setIcon(icon3)
        self.btnReproducirMel.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.btnReproducirMel.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.btnReproducirMel.setObjectName("btnReproducirMel")
        self.gridLayout_18.addWidget(self.btnReproducirMel, 0, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(0, 130, 571, 16))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.line_2 = QtWidgets.QFrame(self.verticalLayoutWidget_4)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_4.addWidget(self.line_2)
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(10, 170, 551, 161))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.graphicsView = QtWidgets.QGraphicsView(self.verticalLayoutWidget_5)
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout_5.addWidget(self.graphicsView)
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(10, 150, 551, 21))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.lblChromagram = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.lblChromagram.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lblChromagram.setAlignment(QtCore.Qt.AlignCenter)
        self.lblChromagram.setObjectName("lblChromagram")
        self.verticalLayout_6.addWidget(self.lblChromagram)
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(390, 330, 171, 31))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.0 = QtWidgets.QPushButton(self.verticalLayoutWidget_7)
        self.0.setObjectName("0")
        self.verticalLayout_7.addWidget(self.0)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(310, 10, 251, 31))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lblMel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.lblMel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lblMel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lblMel.setObjectName("lblMel")
        self.gridLayout_2.addWidget(self.lblMel, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Analisis "))
        self.lblOrig.setText(_translate("MainWindow", "Audio de la Grabación Original"))
        self.btnRepetirOrig.setToolTip(_translate("MainWindow", "Reiniciar Reproducción"))
        self.btnRepetirOrig.setShortcut(_translate("MainWindow", "G"))
        self.btnPausarOrig.setToolTip(_translate("MainWindow", "Pausar Reproducción"))
        self.btnPausarOrig.setShortcut(_translate("MainWindow", "G"))
        self.btnReproducirOrig.setToolTip(_translate("MainWindow", "Iniciar Reproducción"))
        self.btnReproducirOrig.setShortcut(_translate("MainWindow", "G"))
        self.btnRepetirMel.setToolTip(_translate("MainWindow", "Reiniciar Reproducción"))
        self.btnRepetirMel.setShortcut(_translate("MainWindow", "G"))
        self.btnPausarMel.setToolTip(_translate("MainWindow", "Pausar Reproducción"))
        self.btnPausarMel.setShortcut(_translate("MainWindow", "G"))
        self.btnReproducirMel.setToolTip(_translate("MainWindow", "Iniciar Reproducción"))
        self.btnReproducirMel.setShortcut(_translate("MainWindow", "G"))
        self.lblChromagram.setText(_translate("MainWindow", "Chromagrama del Audio"))
        self.0.setText(_translate("MainWindow", "Volver al Menú"))
        self.lblMel.setText(_translate("MainWindow", "Audio de la Melodia Extraída"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
