# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Menu.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.resize(561, 235)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setWindowTitle("Menu")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../../../Downloads/2x/baseline_music_note_black_18dp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(True)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 90, 561, 21))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.line = QtWidgets.QFrame(self.verticalLayoutWidget_2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 190, 271, 41))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.btnGrabar = QtWidgets.QPushButton(self.gridLayoutWidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.btnGrabar.setPalette(palette)
        self.btnGrabar.setAutoFillBackground(True)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../../../../../../Downloads/2x/baseline_mic_black_18dp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnGrabar.setIcon(icon1)
        self.btnGrabar.setAutoDefault(False)
        self.btnGrabar.setDefault(False)
        self.btnGrabar.setFlat(False)
        self.btnGrabar.setObjectName("btnGrabar")
        self.gridLayout.addWidget(self.btnGrabar, 0, 0, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(270, 190, 291, 41))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btnAbrir = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../../../../../../Downloads/2x/baseline_folder_open_black_18dp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAbrir.setIcon(icon2)
        self.btnAbrir.setObjectName("btnAbrir")
        self.gridLayout_2.addWidget(self.btnAbrir, 0, 0, 1, 1)
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(0, 110, 561, 59))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lblMenu2 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.lblMenu2.setMinimumSize(QtCore.QSize(559, 49))
        font = QtGui.QFont()
        font.setFamily("Bell MT")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lblMenu2.setFont(font)
        self.lblMenu2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lblMenu2.setAutoFillBackground(True)
        self.lblMenu2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lblMenu2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lblMenu2.setTextFormat(QtCore.Qt.PlainText)
        self.lblMenu2.setScaledContents(True)
        self.lblMenu2.setWordWrap(True)
        self.lblMenu2.setObjectName("lblMenu2")
        self.verticalLayout_5.addWidget(self.lblMenu2)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 561, 91))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblMenu2_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lblMenu2_2.setMinimumSize(QtCore.QSize(559, 49))
        font = QtGui.QFont()
        font.setFamily("Bell MT")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lblMenu2_2.setFont(font)
        self.lblMenu2_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lblMenu2_2.setAutoFillBackground(True)
        self.lblMenu2_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lblMenu2_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lblMenu2_2.setTextFormat(QtCore.Qt.PlainText)
        self.lblMenu2_2.setScaledContents(True)
        self.lblMenu2_2.setWordWrap(True)
        self.lblMenu2_2.setObjectName("lblMenu2_2")
        self.verticalLayout.addWidget(self.lblMenu2_2)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(0, 170, 561, 21))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.line_2 = QtWidgets.QFrame(self.verticalLayoutWidget_3)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_3.addWidget(self.line_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.btnGrabar.setToolTip(_translate("MainWindow", "Grabar un Audio para Analizar"))
        self.btnGrabar.setText(_translate("MainWindow", "Grabar Nuevo Audio"))
        self.btnAbrir.setToolTip(_translate("MainWindow", "Abrir un Archivo de Audio Existente"))
        self.btnAbrir.setText(_translate("MainWindow", "Abrir Audio Existente"))
        self.lblMenu2.setText(_translate("MainWindow", "Software de Reconocimiento Musical"))
        self.lblMenu2_2.setText(_translate("MainWindow", "Trabajo Practico Final - Soporte a la Gestión de Datos con Programación Visual"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
